# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-SFTP
version:      0.10
version_from: lib/Net/SFTP.pm
installdirs:  site
requires:
    Net::SSH::Perl:                1.24

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
